### ISSUE TITLE
Захостить бота

### ISSUE THREAD

**Issue by ArzaKate** [kuidd/CommitOnBot#7]

**Comment by usynind** [comment]
Найти хостинг.
Развернуть бота.
Полученный URL уже можно будет прописывать в VCS.

**Comment by usynind** [comment]
Пробую heroku.com

**Comment by usynind** [comment]
Для heroku проект должен быть maven. Задача: #18

**Comment by usynind** [comment]
Добавил в зависимости maven-dependency-plugin - это требование heroku (https://devcenter.heroku.com/articles/deploying-java)

**Comment by usynind** [comment]
Захостил: https://commitonbot.herokuapp.com/message.
Скорее всего будет иногда выключаться. Но пока работает!
